name: CI for Angular Application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests against the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v6  # Action to checkout the repository

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Install Angular dependencies

      - name: Build Angular application
        run: npm run build  # Build the Angular application

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: angular-build
          path: dist/  # Specify the build output directory

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: echo "Configuring AWS Credentials"

      - name: Provision Lightsail Instance
        working-directory: infrastructure  # Set the working directory to where main.tf is located
        run: |
          # Initialize Terraform and apply the configuration
          terraform init
          terraform apply -auto-approve
